# Generated by Django 4.1.7 on 2023-03-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('', 'Sexe...'), ('F', 'Femme'), ('H', 'Homme')], default='Femme', max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('language', models.CharField(blank=True, choices=[('', 'Choisir langue...'), ('fr', 'Français'), ('en', 'Anglais'), ('ar', 'Arabe')], default='Français', max_length=50)),
                ('account_type', models.CharField(blank=True, choices=[('', 'Le compte est:'), ('Perso', 'Personnel'), ('Prof', 'Professionel')], default='Personnel (Gratuit)', max_length=50)),
                ('notes', models.CharField(blank=True, default=5, max_length=10)),
                ('accept_rate', models.CharField(blank=True, default=100, max_length=10)),
                ('cancel_rate', models.CharField(blank=True, default=0, max_length=10)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpeg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='profile_img')),
                ('is_updated', models.BooleanField(default=False)),
                ('last_connexion', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_city', to='app.cities')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_country', to='app.countries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.countries'),
        ),
    ]
