# Generated by Django 3.1.5 on 2022-01-25 03:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'User Model',
                'verbose_name_plural': 'Users Model',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.date.today, verbose_name='Date d depart')),
                ('number_of_kg', models.IntegerField(blank=True, default=0)),
                ('price_of_kg', models.IntegerField(blank=True, default=0)),
                ('currency_used', models.CharField(blank=True, max_length=10, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('post_state', models.CharField(blank=True, default='In progress', max_length=50, null=True)),
                ('gp_sent_by', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('deposit_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recovery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_v', to='gp_app.cities')),
                ('arrival_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_c', to='gp_app.countries')),
                ('depart_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_v', to='gp_app.cities')),
                ('depart_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_c', to='gp_app.countries')),
                ('poster', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_kilos', models.IntegerField(blank=True, default=0)),
                ('total_price', models.IntegerField(blank=True, default=0)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reserv_state', models.CharField(blank=True, max_length=20, null=True)),
                ('canceled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reserver_comment', models.CharField(blank=True, max_length=150, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='gp_app.posts')),
                ('poster', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster_id', to=settings.AUTH_USER_MODEL)),
                ('reserver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserver_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.date.today, verbose_name='Date of departure')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_City', to='gp_app.cities')),
                ('arrival_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_Country', to='gp_app.countries')),
                ('depart_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_City', to='gp_app.cities')),
                ('depart_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_Country', to='gp_app.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Femme', 'Femme'), ('Homme', 'Homme')], default='Femme', max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('language', models.CharField(blank=True, choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Arabe', 'Arabe')], default='Français', max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Perso', 'Personnel (Gratuit)'), ('Prof', 'Professionel (Gratuit)')], default='Personnel (Gratuit)', max_length=50)),
                ('notes', models.CharField(blank=True, default=5, max_length=10)),
                ('accept_rate', models.CharField(blank=True, default=100, max_length=10)),
                ('cancel_rate', models.CharField(blank=True, default=0, max_length=10)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatar.jpeg', force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='profile_img')),
                ('is_updated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('note', models.IntegerField(blank=True, default=0)),
                ('com_state', models.CharField(blank=True, max_length=10, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('post_id1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_id_11', to='gp_app.posts')),
                ('post_id11', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_id_111', to='gp_app.posts')),
                ('post_id_com', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_id_1', to='gp_app.posts')),
                ('poster_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster_id_1', to=settings.AUTH_USER_MODEL)),
                ('recepter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recepter_id', to=settings.AUTH_USER_MODEL)),
                ('reserver_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserver_id_1', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gp_app.countries'),
        ),
        migrations.CreateModel(
            name='AlertMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.date.today, verbose_name='Date of departure')),
                ('service', models.CharField(blank=True, max_length=10, null=True)),
                ('alert_state', models.CharField(blank=True, max_length=20, null=True)),
                ('take_departure_date', models.BooleanField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_City_alert', to='gp_app.cities')),
                ('arrival_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_Country_alert', to='gp_app.countries')),
                ('depart_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_City_alert', to='gp_app.cities')),
                ('depart_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_Country_alert', to='gp_app.countries')),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aeroports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gp_app.cities')),
            ],
        ),
    ]
