# https://pypi.org/project/python-decouple/

"""
Django settings for sante_project project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# Configure Django App for Heroku.

import django
from django.utils.encoding import force_str
django.utils.encoding.force_text = force_str

import sys

import django_on_heroku

import os

import dj_database_url

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIRS = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@_^0&j9sxwc8$dex-g9%u@=$dg+x4us*fsa*py41#llqu4eue_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# E_MAIL_HOST_USER = config('EMAIL_HOST_USER')
# E_MAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# E_MAIL_HOST = config('EMAIL_HOST', default='localhost')
# E_MAIL_PORT = config('EMAIL_PORT', default=25, cast=int)

DB_NAME = "" # config('DB_NAME')

DB_USER = "" # config('DB_USER')

DB_PASSWORD = "" # config('DB_PASSWORD')

DB_HOST = "" # config('DB_HOST')

DB_PORT = "" # config('DB_PORT', default=5432, cast=int)



# Email information
EMAIL_HOST = "" # config('EMAIL_HOST', default='localhost') # E_MAIL_HOST

EMAIL_PORT = "" # config('EMAIL_PORT', default=25, cast=int) # E_MAIL_PORT

EMAIL_HOST_USER = "" # config('EMAIL_HOST_USER') # E_MAIL_HOST_USER

EMAIL_HOST_PASSWORD = "" # config('EMAIL_HOST_PASSWORD') # E_MAIL_HOST_PASSWORD

EMAIL_USE_SSL = False

EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # My apps
    'app',
    'crispy_forms',
    'bootstrap4',
    #'bootstrap_datepicker_plus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# AUTH_USER_MODEL = 'app.Users'

ROOT_URLCONF = 'sante_app.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Adding the TEMPLATES_DIRS here
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sante_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

django_on_heroku.settings(locals())

